# Generated by Django 5.2.14 on 2026-05-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "currency_type",
                    models.CharField(
                        choices=[
                            ("IMP", "Imperial Ruble"),
                            ("KER", "Kerenski Ruble"),
                            ("SOV", "Soviet Sovznak"),
                        ],
                        db_index=True,
                        max_length=3,
                    ),
                ),
                (
                    "value_in_gold",
                    models.DecimalField(decimal_places=10, max_digits=25),
                ),
                ("is_milestone", models.BooleanField(db_index=True, default=False)),
                ("event_name", models.CharField(blank=True, max_length=255, null=True)),
                ("event_description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["currency_type", "date"],
                        name="analytics_e_currenc_d7f992_idx",
                    )
                ],
                "unique_together": {("date", "currency_type")},
            },
        ),
    ]
